version: '3'

services:
    amq-client:
        build: amq-client/
        stdin_open: true
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./src:/var/www/html/example
